### ISSUE TITLE
Windows does not handle freeplay.png and freeplay.PNG properly

### ISSUE THREAD

**Issue by JeremyGamer13** [TheShovel/co-funk#24]
**Describe the bug**
On Windows, the `gameAssets/bgart/freeplay.PNG` and `gameAssets/bgart/freeplay.png` files are considered the same file and overwrite eachother

**To Reproduce**
1. download the repo
2. github says you made a change of overriding one `freeplay.PNG` with the other

**Expected behavior**
it should not do that

**Screenshots**
![image](https://github.com/TheShovel/penguin-funk/assets/69337718/c57fae55-330a-4807-b573-e94f4d718c8d)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by TheShovel** [comment]
This has been fixed in the dev branch
I will close this issue when the 2.6 update is released
